//  table.dart
//  Created by JeoJay127
//
extension MapExtension on Map<String, dynamic> {
  String get name => this['name'] ?? '';
}

class ACPITable {
  static const ssdtHPET = {
    'name': 'SSDT-HPET',
    'remark': 'Eliminates IRQ conflicts, typically used for audio codec fixes',
    'note': '''
• HPET (High Precision Event Timer) is a hardware timing module used by the system.
• Under macOS, native HPET configuration on some motherboards causes IRQ (Interrupt Request) conflicts, preventing audio codecs from functioning and leading to instability or boot failures.
• This patch adjusts HPET device ACPI definitions to resolve IRQ conflicts, ensuring macOS properly initializes HPET and restores audio functionality.
   ''',
  };

  static const ssdtECUSBXDesktop = {
    'name': 'SSDT-EC-USBX-DESKTOP',
    'remark': 'Fakes EC and injects USB power properties (Intel Gen 6+ Desktops)',
    'note': '''
• Applies to Intel Gen 6 (Skylake) and newer desktop platforms.
• Disables native EC and injects a fake embedded controller (EC) to satisfy macOS requirements and resolve boot hangs.
• Injects necessary USB power properties to fix sleep/wake and power delivery issues. Equivalent to merging: SSDT-EC-DESKTOP.aml + SSDT-USBX.aml.
        ''',
  };

  static const ssdtECUSBXLaptop = {
    'name': 'SSDT-EC-USBX-LAPTOP',
    'remark': 'Fakes EC without modifying native EC, injects USB power properties (Intel Gen 6+ Laptops)',
    'note': '''
• Applies to Intel Gen 6 (Skylake) and newer laptop platforms.
• Injects a dummy EC without modifying the native EC to preserve laptop power management, battery reporting, and keyboard backlight.
• Injects necessary USB power properties. Equivalent to merging: SSDT-EC-LAPTOP.aml + SSDT-USBX.aml.
''',
  };

  static const ssdtECDesktop = {
    'name': 'SSDT-EC-DESKTOP',
    'remark': 'Fakes EC device (Intel Gen 5 and older Desktops)',
    'note': '''
• Applies to Intel Gen 5 (Broadwell) and older desktop platforms.
• Disables native EC and injects a fake EC device to satisfy macOS requirements and fix boot hangs.
        ''',
  };

  static const ssdtECLaptop = {
    'name': 'SSDT-EC-LAPTOP',
    'remark': 'Fakes EC without modifying native EC (Intel Gen 5 and older Laptops)',
    'note': '''
• Applies to Intel Gen 5 (Broadwell) and older laptop platforms.
• Injects a dummy EC device without modifying the native EC, preserving battery status, thermal control, and keyboard backlight.
''',
  };

  static const ssdtUSBX = {
    'name': 'SSDT-USBX',
    'remark': 'USB power property injection (Intel Gen 6+ and AMD Ryzen)',
    'note': '''
• Applies to Intel Skylake (Gen 6) and newer, Haswell-E/Broadwell-E server platforms, and AMD Ryzen.
• Injects macOS USB power properties (current limits, sleep power) for reliable USB operation and hot-plugging.
• For Laptops: SSDT-EC-LAPTOP.aml + SSDT-USBX.aml = SSDT-EC-USBX-LAPTOP.aml.
• For Desktops: SSDT-EC-DESKTOP.aml + SSDT-USBX.aml = SSDT-EC-USBX-DESKTOP.aml.
''',
  };

  static const ssdtPLUG = {
    'name': 'SSDT-PLUG',
    'remark': 'CPU power management plugin injection (Intel Haswell Gen 4 ~ Gen 11)',
    'note': '''
• Applies to Intel Haswell Gen 4 through Rocket Lake Gen 11 and server platforms. (Auto-detected and generated by RapidSSDT).
• For Intel Alder Lake Gen 12+ and AMD Ryzen, SSDT-PLUG-ALT is used instead.
• Enables native X86PlatformPlugin (plugin-type = 1) for CPU frequency scaling and energy management.
          ''',
  };

  static const ssdtPMC = {
    'name': 'SSDT-PMC',
    'remark': 'Enables native 300-series NVRAM support',
    'note': '''
• Applies to Intel 300-series motherboards (Z370, B360, H370, H310) on Coffee Lake Gen 8/9.
• Enables the Power Management Controller (PMC) to expose native NVRAM support in macOS without EmuVariableUEFI.
''',
  };

  static const ssdtPNLF = {
    'name': 'SSDT-PNLF',
    'remark': 'Adds PNLF backlight control device (Laptops & AIOs)',
    'note': '''
• Injects the ACPI PNLF device required by macOS to regulate laptop display backlight brightness.
• UID = 14: Intel Gen 1 Arrandale, Gen 2 Sandy Bridge, Gen 3 Ivy Bridge.
• UID = 15: Intel Gen 4 Haswell, Gen 5 Broadwell.
• UID = 16: Intel Gen 6 Skylake, Gen 7 Kaby Lake, select Gen 4 Haswell.
• UID = 17 / 18: Custom brightness configurations.
• UID = 19: Intel Gen 8 Coffee Lake ~ Gen 10 Comet Lake & AMD Laptops.
• UID = 99: Other custom device properties.
''',
  };

  static const ssdtALS0 = {
    'name': 'SSDT-ALS0',
    'remark': 'Ambient Light Sensor dummy device (Laptops & AIOs)',
    'note': '''
• Injects a dummy Ambient Light Sensor (ALS0) to enable automatic brightness adjustment and backlight persistence across reboots.
• Applies to All-in-One (AIO) systems and laptops.
          ''',
  };

  static const ssdtXOSI = {
    'name': 'SSDT-XOSI',
    'remark': 'Spoofs OS as Windows to unlock OEM ACPI features (I2C trackpads, etc.)',
    'note': '''
• Redirects _OSI calls to report Windows versions, activating vendor-specific ACPI features intended for Windows (e.g. I2C trackpads, battery status, function keys).
          ''',
  };

  static const ssdtRHUB = {
    'name': 'SSDT-RHUB',
    'remark': 'USB root hub reset and port reconstruction',
    'note': '''
• Disables non-standard RHUB devices on OEM motherboards, forcing macOS to rebuild USB ports properly.
• Commonly used on Intel 400-series desktop motherboards (Asus, Gigabyte) and Ice Lake laptops (Dell, Lenovo).
''',
  };

  static const ssdtBridge = {
    'name': 'SSDT-Bridge',
    'remark': 'Creates missing PCI bridge device paths',
    'note': '''
• Injects missing parent PCI bridges so macOS can locate and address child devices like GPUs, NVMe drives, Wi-Fi cards, and Thunderbolt controllers.
''',
  };

  static const ssdtAPIC = {
    'name': 'SSDT-APIC',
    'remark': 'Fixes APIC Processor IDs to resolve kernel panics (HEDT & Servers)',
    'note': '''
• Corrects Processor IDs in the MADT/APIC table to ensure macOS recognizes CPU cores properly without panic on HEDT platforms (X58, X79, X99, X299).
• Native APIC table must be dropped in OpenCore config when using this patch.
''',
  };

  static const ssdtDMAR = {
    'name': 'SSDT-DMAR',
    'remark': 'Removes reserved memory regions from DMAR for VT-d / AppleVTD support',
    'note': '''
• Removes problematic reserved memory regions in the ACPI DMAR table to enable AppleVTD on Intel VT-d platforms.
• Fixes kernel panics and instability with I225-V, Aquantia 10GbE, and Wi-Fi adapters under macOS Big Sur and newer.
• Native DMAR table must be dropped in ACPI -> Delete.
''',
  };

  static const ssdtSBUSMCHC = {
    'name': 'SSDT-SBUS-MCHC',
    'remark': 'Adds SMBus and Memory Controller devices',
    'note': '''
• Injects SBUS (System Management Bus) and MCHC (Memory Controller) ACPI devices to enable AppleSMBusController support for power management, I2C, and sensors.
''',
  };

  static const ssdtIMEI = {
    'name': 'SSDT-IMEI',
    'remark': 'Fixes Intel Management Engine for mixed Sandy/Ivy Bridge platforms',
    'note': '''
• Fixes IMEI/HECI communication for mixed motherboard/CPU pairs (e.g. Ivy Bridge CPU on 6-series motherboard, or Sandy Bridge CPU on 7-series motherboard).
• Not needed when matching CPU and chipset generations, or on Haswell and newer platforms.
          ''',
  };

  static const ssdtFixShutdown = {
    'name': 'SSDT-FixShutdown',
    'remark': 'Fixes reboot on shutdown or power-off failure',
    'note': '''
• Resolves issues where macOS reboots instead of powering down due to USB controller states during S5 power transition.
• Requires ACPI rename patch: _PTS -> ZPTS.
''',
  };

  static const checkSystemState = {
    'name': 'Check-System-State',
    'remark': 'Checks system sleep state and S3 support (Diagnostic)',
    'note': '''
• Diagnostic check to verify whether the firmware and ACPI tables support S3 sleep.
• Identifies whether the machine is an AOAC (Always On Always Connected / Modern Standby) laptop.
''',
  };

  static const checkAOAC = {
    'name': 'Check-AOAC',
    'remark': 'Checks for AOAC / Modern Standby mode (Diagnostic)',
    'note': '''
• Inspects FACP.aml to determine if the device uses AOAC / Modern Standby.
• AOAC laptops often crash upon entering S3 sleep. Recommended fixes include disabling S3 or adjusting NVMe/ASPM power states.
''',
  };

  static const ssdtGPRW = {
    'name': 'SSDT-GPRW',
    'remark': 'Fixes instant wake caused by USB controllers',
    'note': '''
• Renames GPRW to XPRW to prevent USB devices from immediately waking the system from sleep.
• Wake via power button remains functional.
• Applies to Intel Skylake (Gen 6) and newer platforms.
''',
  };

  static const ssdtUPRW = {
    'name': 'SSDT-UPRW',
    'remark': 'Fixes instant wake caused by UPRW sleep method',
    'note': '''
• Renames UPRW to XPRW for platforms using the UPRW method instead of GPRW.
• Applies to select Skylake and newer OEM motherboards.
''',
  };

  static const ssdtLID = {
    'name': 'SSDT-LID',
    'remark': 'Fixes sleep button handling on laptops',
    'note': '''
• Converts dangerous PNP0C0E sleep button events into safe PNP0C0D lid-close events to prevent kernel panics on sleep.
• Commonly used on laptops.
''',
  };

  static const ssdtWakeScreen = {
    'name': 'SSDT-WakeScreen',
    'remark': 'Fixes black screen requiring keypress on wake',
    'note': '''
• Fixes issues where the internal or external display fails to turn on automatically upon system wake.
''',
  };

  static const ssdtLED = {
    'name': 'SSDT-LED',
    'remark': 'Fixes power LED and microphone LED status on wake (Lenovo laptops)',
    'note': '''
• Fixes breathing LED indicator, power button LED, and F4 microphone mute indicator after waking on Lenovo laptops.
''',
  };

  static const ssdtS3Disable = {
    'name': 'SSDT-S3-DISABLE',
    'remark': 'Disables S3 sleep state to prevent wake crashes or reboot loops',
    'note': '''
• Disables the S3 sleep state in macOS to prevent hard lockups on machines with broken firmware sleep implementations.
• Requires ACPI rename patch: _S3 -> XS3.
''',
  };

  static const ssdtFACP = {
    'name': 'SSDT-FACP',
    'remark': 'Converts warm reboot to cold reset for hardware initialization',
    'note': '''
• Converts soft/warm resets into cold resets, fixing hardware initialization failures (Wi-Fi, Bluetooth, Audio) when rebooting from Windows into macOS.
• Generates ACPI - Patch entries only; no AML file is required.
''',
  };

  static const ssdtGPUSPOOF = {
    'name': 'SSDT-GPU-SPOOF',
    'remark': 'GPU Device ID spoofing',
    'note': '''
• Injects compatible device IDs for AMD discrete GPUs to enable native driver loading under macOS.
• Recommended for GPUs explicitly flagged in RapidEFI compatibility database.
''',
  };

  static const ssdtPCIDISABLE = {
    'name': 'SSDT-PCI-DISABLE',
    'remark': 'PCIe device disabling at ACPI level',
    'note': '''
• Disables unsupported GPUs, NVMe controllers, or wireless cards at the ACPI level.
• Laptop dGPUs prioritize power method disabling (_OFF / _PS3) to save battery and reduce heat.
• Desktop systems use device ID spoofing (IOName) to prevent driver attachment.
''',
  };

  static const ssdtRMNE = {
    'name': 'SSDT-RMNE',
    'remark': 'Virtual Ethernet device for iCloud / Apple services',
    'note': '''
• Injects a virtual NullEthernet device (en0) to satisfy Apple services (iCloud, iMessage, FaceTime) on laptops lacking built-in Ethernet.
  ''',
  };

  static const ssdtGPI0 = {
    'name': 'SSDT-GPI0',
    'remark': 'Enables GPIO controller for I2C trackpads (Laptops)',
    'note': '''
• Enables the GPI0 controller node in ACPI for VoodooI2C trackpad support.
''',
  };

  static const ssdtCPUR = {
    'name': 'SSDT-CPUR',
    'remark': 'CPU device renaming for AMD B550/A520/B650/B850 chipsets (Ryzen)',
    'note': '''
• Injects standard Processor definitions on AMD motherboards that define CPUs in non-standard scopes.
• When custom SSDTs are built, SSDT-PLUG-ALT is used instead.
''',
  };

  static const ssdtPLUGALT = {
    'name': 'SSDT-PLUG-ALT',
    'remark': 'CPU power management for Intel Gen 12+ (Alder Lake+) and AMD Ryzen',
    'note': '''
• Provides custom Processor ACPI objects and plugin-type power management for Intel Alder Lake Gen 12+ and AMD Ryzen.
''',
  };

  static const ssdtAWAC = {
    'name': 'SSDT-AWAC',
    'remark': 'Disables AWAC and forces legacy RTC timer (Intel Gen 8+)',
    'note': '''
• Disables modern AWAC timers and reactivates/fakes the legacy Real Time Clock (RTC) device required by macOS.
• Applies to Intel 300-series (Gen 8) and newer chipsets.
''',
  };

  static const ssdtUNC = {
    'name': 'SSDT-UNC',
    'remark': 'Disables unused uncore devices (Intel X99/X79 HEDT)',
    'note': '''
• Disables unused ACPI devices to prevent IOPCIFamily kernel panics on X79 (C602) and X99 (C612) motherboards.
''',
  };

  static const ssdtRTC0RANGE = {
    'name': 'SSDT-RTC0-RANGE',
    'remark': 'Fixes RTC timer memory range (Intel X99 / X299)',
    'note': '''
• Enables legacy RTC and fixes the memory range definition for X99 and X299 platforms.
• Resolves clock reset, boot freezes, and sleep/wake timer panics.
''',
  };

  static const ssdtDTGP = {
    'name': 'SSDT-DTGP',
    'remark': 'Injects DTGP helper method for ACPI property injection',
    'note': '''
• Injects the universal DTGP helper method required by custom SSDT patches to write _DSM device properties for graphics, audio, and Thunderbolt.
''',
  };

  static const ssdtDMAC = {
    'name': 'SSDT-DMAC',
    'remark': 'Fakes standard DMA controller device',
    'note': '''
• Injects a dummy DMA Controller (PNP0200) to complete the ACPI device tree for legacy LPC bus devices.
''',
  };

  static const ssdtPWRB = {
    'name': 'SSDT-PWRB',
    'remark': 'Fakes standard Power Button device',
    'note': '''
• Injects a dummy Power Button (PNP0C0C) ACPI device to support system sleep/wake actions via power button.
''',
  };

  static const ssdtSLPB = {
    'name': 'SSDT-SLPB',
    'remark': 'Fakes standard Sleep Button device',
    'note': '''
• Injects a dummy Sleep Button (PNP0C0E) ACPI device to support system sleep actions.
''',
  };

  static const ssdtMEM2 = {
    'name': 'SSDT-MEM2',
    'remark': 'Fakes MEM2 memory range device for Intel iGPU',
    'note': '''
• Injects the MEM2 ACPI device to provide iGPU memory mapping on Intel Haswell through Kaby Lake systems with integrated graphics.
''',
  };
}
